title: MettleCI NextGen
description: Documentation for MettleCI running on DataStage NextGen
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://nextgen.mettleci.io

aux_links:
  Legacy Docuemntation: http://docs.mettleci.io/

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_external_links:
  - title: MettleCI Standalone Docs
    url: http://docs.mettleci.io/
  - title: Server-to-Parallel Conversion
    url: http://s2px.mettleci.io/



# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
markup / liquid-based content.
footer_content: "Copyright &copy; 2017-2023 Data Migrators Pty Ltd"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
