title: MettleCI NextGen Docs
description: Documentation for MettleCI running on DataStage NextGen
theme: just-the-docs

url: https://nextgen.mettleci.io

aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Legacy Docuemntation: http://docs.mettleci.io/
