title: MettleCI NextGen
description: Documentation for MettleCI running on DataStage NextGen
theme: just-the-docs

url: https://nextgen.mettleci.io

aux_links:
  Legacy Docuemntation: http://docs.mettleci.io/

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


nav_external_links:
  - title: MettleCI Standalone Docs
    url: http://docs.mettleci.io/
  - title: Server-to-Parallel Conversion
    url: http://s2px.mettleci.io/


